# Generated by Django 4.2.7 on 2023-12-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
                ('blood_group', models.CharField(max_length=3)),
                ('father_name', models.CharField(max_length=50)),
            ],
        ),
    ]
